#!/usr/bin/env python3
"""Guard Namche Shadow Sans counters against collapsing into the outer contour.

The Shadow treatment resolves overlapping shapes with a boolean pass before it
rounds the inner corners. When that pass mistakes an overlapping crossbar for a
counter it subtracts instead of unions, the counter stops being a contour of its
own, and the letter renders as a filled wedge with a hairline notch. The Sans
italic ``A`` shipped that way in every static weight, in the webfonts built from
them, and on the CDN (issue #78).

Contour counts catch that damage for the price of reading the glyph outlines, so
this check runs over every committed Sans release binary and every npm copy —
upright and italic, OTF, TTF, WOFF2 and the variable font. The counts below are
identical across all of them; a glyph that loses (or gains) a contour has had its
topology changed and needs a look before it ships.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.ttLib import TTFont

FONT_SUFFIXES = {".otf", ".ttf", ".woff2"}

# Letters and figures whose design encloses at least one counter. Composites are
# deliberately excluded: the upright statics flatten and overlap-remove their
# accents while the italics keep them as components, so an accented glyph has a
# legitimately different contour count between the two styles.
EXPECTED_CONTOURS = {
    "A": 2,
    "B": 3,
    "D": 2,
    "O": 2,
    "P": 2,
    "Q": 2,
    "R": 2,
    "a": 2,
    "b": 2,
    "d": 2,
    "e": 2,
    "g": 2,
    "o": 2,
    "p": 2,
    "q": 2,
    "zero": 2,
    "four": 2,
    "six": 2,
    "eight": 3,
    "nine": 2,
}

# fonts/: 9 upright + 9 italic in otf/ and ttf/, 18 webfonts + the upright
# variable font. The npm copies are generated by `make copy-npm-fonts` and are
# checked too whenever they are present.
EXPECTED_RELEASE_FILES = 56


def contour_count(glyph_set, name: str) -> int:
    pen = DecomposingRecordingPen(glyph_set)
    glyph_set[name].draw(pen)
    return sum(1 for op, _ in pen.value if op == "moveTo")


def validate_font(path: Path) -> list[str]:
    font = TTFont(path, lazy=True)
    try:
        glyph_set = font.getGlyphSet()
        errors = []
        for name, expected in EXPECTED_CONTOURS.items():
            if name not in glyph_set:
                errors.append(f"{path}: {name} is missing")
                continue
            found = contour_count(glyph_set, name)
            if found != expected:
                errors.append(
                    f"{path}: {name} has {found} contour(s), expected {expected}"
                )
        return errors
    finally:
        font.close()


def release_fonts(root: Path) -> list[Path]:
    release = root / "fonts" / "NamcheShadowSans"
    return sorted(
        path
        for directory in (
            release / "otf",
            release / "ttf",
            release / "webfonts",
            release / "variable",
        )
        for path in directory.glob("*")
        if path.suffix.lower() in FONT_SUFFIXES
    )


def generated_fonts(root: Path) -> list[Path]:
    directories = [
        root / "fonts" / "NamcheShadowSans" / "webfonts" / "subsets",
        root / "packages" / "next" / "dist" / "fonts" / "namche-shadow-sans",
    ]
    return sorted(
        path
        for directory in directories
        if directory.is_dir()
        for path in directory.glob("*")
        if path.suffix.lower() in FONT_SUFFIXES
    )


def validate_release(root: Path) -> tuple[list[str], int]:
    release = release_fonts(root)
    errors: list[str] = []
    if len(release) != EXPECTED_RELEASE_FILES:
        errors.append(
            f"expected {EXPECTED_RELEASE_FILES} Sans release fonts; "
            f"found {len(release)}"
        )
    paths = release + generated_fonts(root)
    for path in paths:
        errors.extend(validate_font(path))
    return errors, len(paths)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    args = parser.parse_args()
    errors, checked = validate_release(args.root.resolve())
    if errors:
        print("Sans counter validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(
        f"Verified {len(EXPECTED_CONTOURS)} counter-bearing glyphs "
        f"in {checked} Sans release/npm fonts"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
